export const themeChart = [
  {
    label: "Minimog",
    fill: false,
    borderColor: "#ED2B33FF",
    tension: 0.3,
    url: "https://themeforest.net/item/minimog-the-high-converting-shopify-theme/33380968",
  },
  {
    label: "Avone",
    fill: false,
    borderColor: "#A01855FF",
    tension: 0.3,
    url: "https://themeforest.net/item/avone-multipurpose-shopify-theme/24276567",
  },
  {
    label: "Ella",
    fill: false,
    borderColor: "#2C5F2D",
    tension: 0.3,
    url: "https://themeforest.net/item/ella-responsive-shopify-template/9691007",
  },
  {
    label: "Wokiee",
    fill: false,
    borderColor: "#5B84B1FF",
    tension: 0.3,
    url: "https://themeforest.net/item/wokiee-multipurpose-shopify-theme/22559417",
  },
  {
    label: "Kalles",
    fill: false,
    borderColor: "#5F4B8BFF",
    tension: 0.3,
    url: "https://themeforest.net/item/kalles-clean-versatile-shopify-theme/26320622",
  },
  {
    label: "Shella",
    fill: false,
    borderColor: "#A07855FF",
    tension: 0.3,
    url: "https://themeforest.net/item/shella-ultimate-fashion-responsive-shopify-theme/22804833",
  },
  {
    label: "Gecko",
    fill: false,
    borderColor: "#101820FF",
    tension: 0.3,
    url: "https://themeforest.net/item/gecko-responsive-shopify-theme/21398578",
  },
];
