import { format } from 'date-fns';
import { utcToZonedTime } from 'date-fns-tz';

const currentDate = utcToZonedTime(new Date(), 'Australia/Sydney');
export const shopifyThemes = [
  {
    url: 'https://themeforest.net/item/minimog-the-high-converting-shopify-theme',
    themeId: 33380968,
    name: 'Minimog',
    fixedSales: 2608,
    fixedReviews: 322,
    created_at: format(currentDate, 'MM/dd/yyyy'),
    fill: false,
    color: '#ED2B33FF',
    tension: 0.3,
  },
  {
    url: 'https://themeforest.net/item/avone-multipurpose-shopify-theme',
    themeId: 24276567,
    name: 'Avone',
    fixedSales: 6351,
    fixedReviews: 421,
    created_at: format(currentDate, 'MM/dd/yyyy'),
    fill: false,
    color: '#A01855FF',
    tension: 0.3,
  },
  {
    url: 'https://themeforest.net/item/ella-responsive-shopify-template',
    themeId: 9691007,
    name: 'Ella',
    fixedSales: 24085,
    fixedReviews: 819,
    created_at: format(currentDate, 'MM/dd/yyyy'),
    fill: false,
    color: '#2C5F2D',
    tension: 0.3,
  },
  {
    url: 'https://themeforest.net/item/wokiee-multipurpose-shopify-theme',
    themeId: 22559417,
    name: 'Wokiee',
    fixedSales: 19245,
    fixedReviews: 449,
    created_at: format(currentDate, 'MM/dd/yyyy'),
    fill: false,
    color: '#5B84B1FF',
    tension: 0.3,
  },
  {
    url: 'https://themeforest.net/item/kalles-clean-versatile-shopify-theme',
    themeId: 26320622,
    name: 'Kalles',
    fixedSales: 7416,
    fixedReviews: 1096,
    created_at: format(currentDate, 'MM/dd/yyyy'),
    fill: false,
    color: '#5F4B8BFF',
    tension: 0.3,
  },
  {
    url: 'https://themeforest.net/item/shella-ultimate-fashion-responsive-shopify-theme',
    themeId: 22804833,
    name: 'Shella',
    fixedSales: 9618,
    fixedReviews: 223,
    created_at: format(currentDate, 'MM/dd/yyyy'),
    fill: false,
    color: '#A07855FF',
    tension: 0.3,
  },
  {
    url: 'https://themeforest.net/item/gecko-responsive-shopify-theme',
    themeId: 21398578,
    name: 'Gecko',
    fixedSales: 6666,
    fixedReviews: 704,
    created_at: format(currentDate, 'MM/dd/yyyy'),
    fill: false,
    color: '#101820FF',
    tension: 0.3,
  },
  {
    url: 'https://themeforest.net/item/unsen-multipurpose-shopify-theme-os20',
    themeId: 39744835,
    name: 'Unsen',
    fixedSales: 114,
    fixedReviews: 60,
    created_at: format(currentDate, 'MM/dd/yyyy'),
    fill: false,
    color: '#15C39A',
    tension: 0.3,
  },
];

export const wpThemes = [
  {
    url: 'https://themeforest.net/item/minimog-the-high-converting-ecommerce-wordpress-theme',
    themeId: 36947163,
    name: 'MinimogWP',
    fixedSales: 2302,
    fixedReviews: 91,
    created_at: format(currentDate, 'MM/dd/yyyy'),
    fill: false,
    color: '#ED2B33FF',
    tension: 0.3,
  },
  {
    url: 'https://themeforest.net/item/flatsome-multipurpose-responsive-woocommerce-theme',
    themeId: 5484319,
    name: 'Flatsome',
    fixedSales: 207982,
    fixedReviews: 7162,
    created_at: format(currentDate, 'MM/dd/yyyy'),
    fill: false,
    color: '#A01855FF',
    tension: 0.3,
  },
  {
    url: 'https://themeforest.net/item/woodmart-woocommerce-wordpress-theme',
    themeId: 20264492,
    name: 'WoodMart',
    fixedSales: 52743,
    fixedReviews: 2137,
    created_at: format(currentDate, 'MM/dd/yyyy'),
    fill: false,
    color: '#2C5F2D',
    tension: 0.3,
  },
  {
    url: 'https://themeforest.net/item/porto-responsive-wordpress-ecommerce-theme',
    themeId: 9207399,
    name: 'Porto',
    fixedSales: 79056,
    fixedReviews: 3505,
    created_at: format(currentDate, 'MM/dd/yyyy'),
    fill: false,
    color: '#5B84B1FF',
    tension: 0.3,
  },
  {
    url: 'https://themeforest.net/item/xstore-responsive-woocommerce-theme',
    themeId: 15780546,
    name: 'XStore',
    fixedSales: 34868,
    fixedReviews: 1496,
    created_at: format(currentDate, 'MM/dd/yyyy'),
    fill: false,
    color: '#5F4B8BFF',
    tension: 0.3,
  },
  {
    url: 'https://themeforest.net/item/kalles-versatile-woocommerce-theme',
    themeId: 34529223,
    name: 'Kalles',
    fixedSales: 1015,
    fixedReviews: 114,
    created_at: format(currentDate, 'MM/dd/yyyy'),
    fill: false,
    color: '#00EE00',
    tension: 0.3,
  },
  {
    url: 'https://themeforest.net/item/electro-electronics-store-woocommerce-theme',
    themeId: 15720624,
    name: 'Electro',
    fixedSales: 22229,
    fixedReviews: 911,
    created_at: format(currentDate, 'MM/dd/yyyy'),
    fill: false,
    color: '#FFFF00',
    tension: 0.3,
  },
  {
    url: 'https://themeforest.net/item/rey-multipurpose-woocommerce-theme',
    themeId: 24689383,
    name: 'Rey',
    fixedSales: 6007,
    fixedReviews: 369,
    created_at: format(currentDate, 'MM/dd/yyyy'),
    fill: false,
    color: '#FFCCFF',
    tension: 0.3,
  },
  {
    url: 'https://themeforest.net/item/savoy-minimalist-ajax-woocommerce-theme',
    themeId: 12537825,
    name: 'Savoy',
    fixedSales: 13667,
    fixedReviews: 520,
    created_at: format(currentDate, 'MM/dd/yyyy'),
    fill: false,
    color: '#006699',
    tension: 0.3,
  },
];

export const themeShop = process.env.NEXT_PUBLIC_PRODUCT === 'minimogwp' ? wpThemes : shopifyThemes;
